export const dir = {
    'N': 'Bắc',
    'NNE': 'Bắc Đông Bắc',
    'NE': 'Đông Bắc',
    'ENE': 'Đông Đông Bắc', 
    'E': 'Đông',
    'ESE': 'Đông Đông Nam',
    'SE': 'Đông Nam',
    'SSE': 'Nam Đông Nam',
    'S': 'Nam', 
    'SSW': 'Nam Tây Nam',
    'SW': 'Tây Nam',
    'WSW':  'Tây Tây Nam', 
    'W': 'Tây', 
    'WNW': 'Tây Tây Bắc', 
    'NW': 'Tây Bắc', 
    'NNW': 'Bắc Tây Bắc',
}
export const dirE = {
    'N': 'North',
    'NNE': 'North East North',
    'NE': 'North East',
    'ENE': 'East North East',
    'E': 'East',
    'ESE': 'South East South',
    'SE': 'South East',
    'SSE': 'South South East',
    'S': 'South',
    'SSW': 'South South West',
    'SW': 'South West',
    'WSW': 'West South West',
    'W': 'West',
    'WNW': 'West North West',
    'NW': 'North West',
    'NNW': 'North North West',
}